/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../theme/colors`; params?: Router.UnknownInputParams; } | { pathname: `/../theme/typography`; params?: Router.UnknownInputParams; } | { pathname: `/../theme/radius`; params?: Router.UnknownInputParams; } | { pathname: `/../theme/spacing`; params?: Router.UnknownInputParams; } | { pathname: `/../theme/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Typography`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Button`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Card`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ProgressBar`; params?: Router.UnknownInputParams; } | { pathname: `/../components/CircularProgress`; params?: Router.UnknownInputParams; } | { pathname: `/../components/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/book/[id]`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../theme/colors`; params?: Router.UnknownOutputParams; } | { pathname: `/../theme/typography`; params?: Router.UnknownOutputParams; } | { pathname: `/../theme/radius`; params?: Router.UnknownOutputParams; } | { pathname: `/../theme/spacing`; params?: Router.UnknownOutputParams; } | { pathname: `/../theme/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Typography`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Button`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Card`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ProgressBar`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/CircularProgress`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/book/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../theme/colors${`?${string}` | `#${string}` | ''}` | `/../theme/typography${`?${string}` | `#${string}` | ''}` | `/../theme/radius${`?${string}` | `#${string}` | ''}` | `/../theme/spacing${`?${string}` | `#${string}` | ''}` | `/../theme/index${`?${string}` | `#${string}` | ''}` | `/../components/Typography${`?${string}` | `#${string}` | ''}` | `/../components/Button${`?${string}` | `#${string}` | ''}` | `/../components/Card${`?${string}` | `#${string}` | ''}` | `/../components/ProgressBar${`?${string}` | `#${string}` | ''}` | `/../components/CircularProgress${`?${string}` | `#${string}` | ''}` | `/../components/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/index${`?${string}` | `#${string}` | ''}` | `/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/book/[id]${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../theme/colors`; params?: Router.UnknownInputParams; } | { pathname: `/../theme/typography`; params?: Router.UnknownInputParams; } | { pathname: `/../theme/radius`; params?: Router.UnknownInputParams; } | { pathname: `/../theme/spacing`; params?: Router.UnknownInputParams; } | { pathname: `/../theme/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Typography`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Button`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Card`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ProgressBar`; params?: Router.UnknownInputParams; } | { pathname: `/../components/CircularProgress`; params?: Router.UnknownInputParams; } | { pathname: `/../components/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/book/[id]`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
